### ISSUE TITLE
`keep_val` is ignored for the last instruction

### ISSUE THREAD

**Issue by ps-cd** [nlyu1/NI-experiment-control#3]
When compiled without `stop_time`, `keep_val=False` has no effect for the last instruction - the final value is kept instead of setting to 0. The same unexpected behavior for both AO and DO channels. However, it works when using `stop_time` with some buffer. 

Minimal example to reproduce ([link to the notebook](https://github.com/nlyu1/NI-experiment-control/blob/py_api/nistreamer/test/keep_val%20bug.ipynb)):

```Python
from nistreamer.streamer import NIStreamer

ni_streamer = NIStreamer()
ao_card = ni_streamer.add_ao_card(max_name='PXI1Slot3', samp_rate=1e6)
my_ao = ao_card.add_chan(chan_idx=0)

ni_streamer.clear_edit_cache()

# Instr 1
my_ao.constant(t=1, dur=1, val=0.5)

# Instr 2
my_ao.sine(
    t=3, dur=1,
    amp=1.0, freq=10.12345678, phase=1.23,
    keep_val=False
)

# Instr 3
my_ao.constant(t=5, dur=1, val=1.5, keep_val=False)

# Instr 4
my_ao.constant(t=6.5, dur=0.5, val=2.0, keep_val=False)

# comment out subsequent instructions from the end 
# to see that neither resets to 0 when it is at the end of the sequence
```

**Comment by nlyu1** [comment]
This is designed behavior since `keep_val` has no effect on the last instruction (beyond which the streamer cannot control the device). Use `add_reset_tick()` to explicitly invoke the desired behavior. See `nistreamer/debug_scripts/final_keep_val.ipynb`.

**Comment by nlyu1** [comment]
-
