### ISSUE TITLE
Instruction collision panics

### ISSUE THREAD

**Issue by ps-cd** [nlyu1/NI-experiment-control#4]
There are several types of situations when collision check raises `PanicException` for physically meaningful pulses:

1. Back-to-back pulses

2. Final pulse end colliding with auto-calculated `end_time`

See this notebook to reproduce ([link](https://github.com/nlyu1/NI-experiment-control/blob/main/nistreamer/test/Collision%20check%20bugs.ipynb)).

**Comment by ps-cd** [comment]
[back-to-back collision error] one could try relaxing overlap check to allow for +-1 tick overlap.

**Comment by nlyu1** [comment]
Resolved. `add_instr` now allows a flexible rigid shift of <1ms which makes sure not to lose the signal.  Did not get to reproduce the second final pulse bug. Tested using `nistreamer/debug_scripts/flexible_tick.ipynb`.

**Comment by ps-cd** [comment]
@nlyu1 

Do not agree with this solution. It can lead to very serious problems.

These panics are fundamentally coming from rounding errors when the physical (f64) pulse edges are falling within one clock tick from each other. 

The proposed solution does cover that. But in addition, it will also "fix" the cases of actual user mistakes when they indeed try to insert pulses with physical overlap. In such cases, moving pulses is not acceptable for a few reasons:

1. Duration of the intervals between pulses is just as critical as duration of pulses themselves - intervals are a part of the sequence and must be precise. Silently altering them can easily lead to confusion and nonsensical/misinterpreted experiment results.
   
2. Shifting the conflicting pulse by any amount (especially as huge as 1 ms) may lead to a collision with some other pulse inserted later, which was otherwise completely legitimate. If such "induced" collision happens, it will panic at adding this other legitimate pulse and not the original conflicting one making it harder to spot the actual mistake in the user script.

**Comment by ps-cd** [comment]
As additional notes, there are two mistakes here:

1. If shift is done, the pulse is shifted by the whole `delta` of 1ms and not by `conflict_ticks`
2. A typo in [this line](https://github.com/nlyu1/NI-experiment-control/blob/2679a6ec0e6fcaa738dde2c6b35574eb339b37f9/nicompiler_backend/src/channel.rs#L345C17-L345C79): `start_pos + delta` instead of `next.start_pos + delta`

**Comment by ps-cd** [comment]
Instead of shifting pulses, I would consider:
- either trim whichever of the pulses to the nearest non-overlapping tick
- or relaxing from strict to inclusive inequality (this should result in effective trimming when calculating samples - the sample for the overlap tick will be calculated according to one of the instructions but not the other).

It is acceptable because the fundamental issue is that neighboring pulse edges are requested to be too close by, split by an interval below physical time resolution of the digital hardware. The best hardware can do for back-to-back pulses - output the approximate-last value of the left instruction on one tick and then the approximate-first value of the right instruction on the next tick. So pulses will have to be trimmer/extended to match the rigid clock grid anyways. This approximation/rounding is unavoidable. 

For analog outputs, there is an additional factor - analog output bandwidth is intentionally restricted such that voltage step rise time is commensurate with the clock period. It is done to make the output signal smooth. So skipping or adding a single non-zero point at the edge of the pulse will not affect the actual signal shape much.

**Comment by nlyu1** [comment]
Thanks for catching the bug fix bugs! The unintended behavior has been fixed

Still disagree with the trim solution. 
1. Silently ignoring an intended one-tick `go_high` or `go_low` is much more serious than ignoring unspecified intervals. The user can explicitly specify interval value if they really matter. 
2. A more fundamental reason: the trim solution cannot handle back-to-back `go-*` with conflicting rounds elegantly without altering intended behavior.
