### ISSUE TITLE
`calc_signal()` panics when there are no instructions for a channel 

### ISSUE THREAD

**Issue by ps-cd** [nlyu1/NI-experiment-control#8]
Proposed solution:
- check this channel's edit cache
- if empty, return array of 0s.

**Comment by nlyu1** [comment]
Can you provide code replicating the behavior? The current test below in `integrated_test.rs` should panic when the device contains no signals to compute. If there is a better behavior we can add that in (but what would be the dimensions of the returned zero array?

```
fn empty_calc_signal() {
    let mut exp = Experiment::new();
    // Define devices and associated channels
    exp.add_do_device("PXI1Slot6", 1e7);
    exp.add_do_channel("PXI1Slot6", 0, 0);

    exp.compile();
    exp.device_calc_signal_nsamps("PXI1Slot6", 0, 10, 100, false, false);
}
```
