### ISSUE TITLE
`low()` goes low but doesn't go back high

### ISSUE THREAD

**Issue by ps-cd** [nlyu1/NI-experiment-control#9]
**Expected behavior**
For digital channels, `low(t, dur)` instruction should set output to low at time `t` and then set it to high after time `dur`.

**Actual behavior**
It sets value from high to low but doesn't change it back to high after `dur`.

**Comment by nlyu1** [comment]
Added `default_value` method for all channels. The rust backend expects `f64` default value and checks that those provided to DO channels are `0` or `1`, otherwise panics. The python frontend defaults AO default values to `0` and DO default values to `False`.
